# Auto Generated Dockerfile

FROM ballerina/ballerina-runtime:0.990.3
LABEL maintainer="dev@ballerina.io"

COPY employee-service.balx /home/ballerina 

EXPOSE  9090
CMD ballerina run  employee-service.balx
